
// This file has been generated by the GUI designer. Do not modify.
namespace GuiClient
{
	public partial class RemoteWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HButtonBox hbuttonbox1;

		private global::Gtk.Button btnClose;

		private global::Gtk.EventBox eventBox;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GuiClient.RemoteWindow
			this.Name = "GuiClient.RemoteWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("RemoteWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GuiClient.RemoteWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox();
			this.hbuttonbox1.Name = "hbuttonbox1";
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnClose = new global::Gtk.Button();
			this.btnClose.CanFocus = true;
			this.btnClose.Name = "btnClose";
			this.btnClose.UseUnderline = true;
			this.btnClose.Label = global::Mono.Unix.Catalog.GetString("Schließen");
			this.hbuttonbox1.Add(this.btnClose);
			global::Gtk.ButtonBox.ButtonBoxChild w1 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnClose]));
			w1.Expand = false;
			w1.Fill = false;
			this.vbox1.Add(this.hbuttonbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.eventBox = new global::Gtk.EventBox();
			this.eventBox.CanFocus = true;
			this.eventBox.Name = "eventBox";
			this.vbox1.Add(this.eventBox);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.eventBox]));
			w3.Position = 1;
			w3.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.btnClose.Clicked += new global::System.EventHandler(this.OnBtnCloseClicked);
		}
	}
}
